layout_spectrum: 0.9421642
typography_spectrum: 0.2742537
color:
  saturation: 0.4808769
  lightness: 0.2033582
  brandStrength: 0.9406508
  brandColors:
    - '#ADCEEA'
    - '#909CAC'
    - '#15160E'
    - '#394B5C'
    - '#CFBD5C'
  rhythmicContrast: 0.3903854
name: Rain Master
